### ISSUE TITLE
The program is not responding

### ISSUE THREAD

**Issue by ruafelianna** [akanshSirohi/ShareX#11]
Hello!

When I don't give to the app the permission to use camera, the UI of the app does not respond. I tried it on two devices, the behaviour is the same. I don't need the app to scan QR codes, so I don't want to give it the permission to use camera. I hope you can fix this.

The app is still wonderful! Cheers!

**Comment by akanshSirohi** [comment]
Sorry for late reply, as this is my side project and I am not actively working on it, so it takes time to solve issues on this app. I will surely fix that on next update. Thanks for your feedback!
