### ISSUE TITLE
Unable to select files in Private mode

### ISSUE THREAD

**Issue by kabe81** [akanshSirohi/ShareX#35]
With Private Mode enabled I am unable to add files using + and  folder icon. Selection of media files works fine. All permissions have been granted.

I am using GrapheneOS with pixel 6a. I suspect this could be related to the way Grapheneos handles storage permission.

**Comment by akanshSirohi** [comment]
@kabe81 Sorry to say, but I have no device to test this app for Graphene OS, as it only supports Pixel devices for now. I will still look into it and try to fix it in the next update.

**Comment by DocSniper** [comment]
I have the same problem with LineageOS 20 (on a Oneplus phone).
