### ISSUE TITLE
Allow Access to External Storage

### ISSUE THREAD

**Issue by gracie95** [akanshSirohi/ShareX#43]
Only Internal Storage here allowed now.

**Comment by akanshSirohi** [comment]
Thanks for your suggestion, I will try to implement that feature in future updates.

**Comment by akanshSirohi** [comment]
@gracie95 Thanks for suggesting this enhancement, it's added in the app and currently being tested. It will be visible in the next update soon. Feel free to reach me anytime if you got more suggestions.
