### ISSUE TITLE
Can't select file

### ISSUE THREAD

**Issue by DevoMan00** [akanshSirohi/ShareX#55]
Private mode is for sending only selected files, but for some reason I can't select files, only media (pictures/videos).

**Steps To Reproduce**
1. Locate the "+" icon
2. Click on it
3. Locate the folder icon
4. Click on it

**Expected behavior**
The file explorer would pop up, or if the user has multiple then a popup will appear prompting the user to choose their preferred file explorer. (Some might have Google files as well as the default file explorer from Android)

**Device Details (please complete the following information):**
 - Version: Android 13
 - Device: Samsung S22
 - App Version: 2.3.7

**Comment by akanshSirohi** [comment]
@DevoMan00 Thanks for the report! I will fix it as soon as possible.
