### ISSUE TITLE
Choosing file is not working while private mode enabled

### ISSUE THREAD

**Issue by gracie95** [akanshSirohi/ShareX#65]
**Describe the bug**
While pressing the add file, file manager does not open. But, when pressing add media, it does.

**Steps To Reproduce**
1. Make sure both devices are conected
2. Go to settings
3. Enable private mode

**Expected behavior**
The file picker must work as media picker.

**Device Details (please complete the following information):**
 - Version: Android 13
 - Device: Galaxy A52 4G
 - App Version 2.3.7

**Comment by akanshSirohi** [comment]
@gracie95 This bug is already fixed in the coming update v2.3.8. You can check the progress here: https://github.com/users/akanshSirohi/projects/1
It will be released in a day or two.
