### ISSUE TITLE
add app to android's share menu

### ISSUE THREAD

**Issue by pokegamer5547** [akanshSirohi/ShareX#71]
**Is your feature request related to a problem? Please describe.**
Lets say we want to share a file from whatsapp to someone without internet. The app is missing in share menu.

**Describe the solution you'd like**
Having app in share menu would.make it easier and, that is how most sharing apps work as well.

**Comment by akanshSirohi** [comment]
@pokegamer5547 Thanks for your suggestion but this app works in a different way than other apps, also there are some kind of security limitations in Android latest versions, so this feature for now is not possible to be implemented for now, but I will take a look at it in future if it will be possible somehow.
