### ISSUE TITLE
Doesn't work at all.  

### ISSUE THREAD

**Issue by vladimirov-s** [akanshSirohi/ShareX#76]
The application shows me a request for some permissions, which are not even in the properties of this application at all.  Allowing everything (file editors, notepads, banking applications!!!!!!!!, etc.) does not lead to the expected operation of the application.  If I go to the application properties, there should be an “access to files” item to access files, but there isn’t one.  Menu items are not clickable.  The start button does nothing.

On the third picture there should be a "file access" item.  Everything you've done is rubbish.  All this does not need to be resolved.  I'm against.

![Screenshot_2023-12-07-09-47-38-67_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/akanshSirohi/ShareX/assets/101799674/5c74ac44-207c-4246-b30b-3e6315cb64ef)

![Screenshot_2023-12-07-09-47-27-69_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/akanshSirohi/ShareX/assets/101799674/edfd3f5d-dabb-4f85-99f9-83a6d3b410ca)

![Screenshot_2023-12-07-09-48-05-87_e6871cd13ad370b30dca80a8c4050ac0.jpg](https://github.com/akanshSirohi/ShareX/assets/101799674/992baff5-45bf-4f46-9413-8d2a2294d26d)

**Device Details (please complete the following information):**
 - android 13
 - Device: Realme GT Neo2T 12/256
 - App Version v2.3.7

**Comment by akanshSirohi** [comment]
@vladimirov-s Sorry to hear your concern but this app works perfectly on Android 13 as of now. This app requires permissions that are required for the app functionality, like battery optimization override for keep running in background during large file transfer and all files access. Please read the instructions carefully before using the app then use it. 

I am not stealing any information from you, you can download Github latest release build from FDroid also if you think that somehow I am modifying the source of the app.
